#ifndef REQUESTTYPE_H
#define REQUESTTYPE_H

enum class RequestType {
   CREATE_REQUEST,
   UPLOAD_PROFILE_PICTURE_REQUEST,
   LOGIN_REQUEST,
   TYPING_REQUEST,
   FETCH_MESSAGES_REQUEST,
   MESSAGE_REQUEST,
   MESSAGE_ACK_REQUEST,
   SEEN_REQUEST,
   UPLOAD_IMAGE_MESSAGE_REQUEST,
   MESSAGE_IMAGE_FINALIZE_REQUEST,
   SEEN_UPDATE_REQUEST,
   FIRST_MESSAGE_REQUEST,
   RECENT_CHATROOM_REQUEST,
   FETCH_IMAGES_FOR_CHAT_REQUEST,
   DISCONNECT_REQUEST,
   LOGOUT_REQUEST,
   AUTH_REQUEST,  
   ERROR_REQUEST,
   SEARCH_QUERY_REQUEST,
   REACTION_REQUEST,
   MESSAGE_SEARCH_REQUEST
};
#endif
