#ifndef RESPONSETYPE_H
#define RESPONSETYPE_H

enum class ResponseType {
    AUTH_RESPONSE,
    LOGIN_RESPONSE,
    LOGIN_FAILED,
    TYPING_RESPONSE,
    CREATE_RESPONSE,
    CREATE_FAILED,
    SEEN_RESPONSE,
    MESSAGE_ACK_RESPONSE,
    UPLOAD_IMAGE_MESSAGE_FINISHED_RESPONSE,
    SEEN_UPDATE_RESPONSE,
    MESSAGE_IMAGE_FINALIZE_RESPONSE,
    UPLOAD_IMAGE_MESSAGE_RESPONSE,
    USER_NOT_FOUND,
    USER_OFFLINE,
    MESSAGE_RESPONSE,
    MESSAGE_RECEIVED,
    FETCH_MESSAGES_RESULT,
    FETCH_MESSAGES_RESPONSE,
    ACTIVE_STATUS_RESPONSE,
    ACTIVE_STATUS_RESPONSE_FAIL,
    CHATROOM_ID_RESPONSE,
    UPLOAD_PROFILE_PICTURE_FINISHED_RESPONSE,
    UPLOAD_PROFILE_PICTURE_RESPONSE,
    RECENT_CHATROOM_RESPONSE,
    ERROR_RESPONSE,
    FETCH_IMAGES_FOR_CHAT_RESPONSE,
    PEER_USER_NOT_FOUND_RESPONSE,
    SEARCH_QUERY_RESPONSE,
    REACTION_RESPONSE,
    MESSAGE_SEARCH_RESPONSE
};
#endif

